name: Go
on:
  push:
#    branches:
#    - master
    tags:
    - 'v*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build all binaries
      run: |
        make all-build

    - name: Publish Binaries
#      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/mystico*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Login
#      if: startsWith(github.ref, 'refs/tags/')
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and Push Docker
#      if: startsWith(github.ref, 'refs/tags/')
      run: |
        make docker
